#!/bin/sh

##
# PER TSCHAK
# * take the NES file
# * strip off first 16 bytes
# * last 8192 bytes are CHR ROM
# * the remaining 32768 bytes are PRG ROM
# * split PRG file into 16384 byte chunks using split -b16384 and copy into place
# * put the CHR into one of the empty banks at the end (look for empty16.prg incbins), and pad out to 16384 bytes (there is a blank8k file that you can cat onto the end to do that. 
# after that, the binary is in the cartridge, you can then do what you need to do to get it done.
##

##
# It basically just makes it so that it's a clean break right down the middle.
# compile gives you a 32K NES rom, strip off the header, and split right down the middle with -b16384,
# take those two files and plop them in banks.
##

FILE=$1
base=`basename ${FILE} .nes`

echo "Stripping ${FILE}..."

# New files....
outfile=${base}.out
prgfile=${base}.prg1
prg2file=${base}.prg2

# Strip...
echo "Skipping first 16 bytes -- Remove header"
dd if=${FILE} bs=1 skip=16 of=${outfile}

echo "Grab the PRG section -- Get the actual application"
dd if=${outfile} bs=1 count=16384 of=${prgfile}

echo "Grab the CHR section -- Get the tiles, etc..."
dd if=${outfile} bs=1 skip=16384 count=16384 of=${prg2file}

echo "Remove temp files"
rm -rf ${outfile}

echo "Complete."
exit 0
